services:
  worker:
    container_name: worker
    build:
      context: ./
      dockerfile: worker/Dockerfile
      args:
        - PHP_USER=temporal
        - PHP_UID=${PHP_UID:-1000}
        - PHP_GID=${PHP_GID:-1000}
    volumes:
     - ../../apps/all-in-one:/var/www
    environment:
      - TEMPORAL_TASK_QUEUE=temporal.queue
      - TEMPORAL_SERVER_ENDPOINT=temporal.addr:7233
      - TELEMETRY_DRIVER=otel
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://collector.addr:4318
      - OTEL_PHP_TRACES_PROCESSOR=simple
      - TEMPORAL_HOST=temporal.addr
      - OTEL_HOST=collector.addr
      - OTEL_SERVICE_NAME=app-temporal-samples
    networks:
      - temporal-apps
    ports:
      - 9400:80
    extra_hosts:
      - "temporal.addr=host-gateway"
      - "collector.addr=host-gateway"
    command: [ "/usr/local/bin/rr", "serve", "-c", "/var/www/rr.yaml" ]

networks:
  temporal-apps:
    driver: bridge
    name: temporal-apps
