parameters:
    # Default value for the Temporal collector endpoint
    env(OTEL_COLLECTOR_ENDPOINT): 'http://collector.addr:4317'
    # Default value for the Temporal server endpoint
    env(TEMPORAL_SERVER_ENDPOINT): 'http://temporal.addr:7233'

services:
    # default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services.
        autowire: true

    Temporal\OpenTelemetry\Tracer:
        factory: ['App\Temporal\Factory\RuntimeFactory', 'tracer']
        arguments:
            $serviceName: 'interceptors-sample-worker'
            $collectorEndpoint: '%env(OTEL_COLLECTOR_ENDPOINT)%'

    Temporal\Client\WorkflowClientInterface:
        public: true # We need to have a facade for this service.
        factory: ['App\Temporal\Factory\RuntimeFactory', 'client']
        arguments:
            $serverAddress: '%env(TEMPORAL_SERVER_ENDPOINT)%'

    # Temporal classes
    App\Temporal\:
        resource: '../../src/Temporal/'
