parameters:
  # Default value for the collector endpoint
  env(OTEL_COLLECTOR_ENDPOINT): 'http://collector.addr:4317'

services:
    # default configuration for services in *this* file
    _defaults:
        # Automatically injects dependencies in your services.
        autowire: true
        bind:
            $container: '@service_container'
            # Queue for the activity workers
            $activityTaskQueue: '%env(ACTIVITY_TASK_QUEUE)%'

    Temporal\OpenTelemetry\Tracer:
        shared: false
        factory: ['App\Temporal\Factory\RuntimeFactory', 'tracer']
        arguments:
            $serviceName: 'activity-worker-interceptor'
            $collectorEndpoint: '%env(OTEL_COLLECTOR_ENDPOINT)%'

    Temporal\WorkerFactory:
        factory: [null, 'create']

    Temporal\Worker\WorkerFactoryInterface: '@Temporal\WorkerFactory'

    Temporal\Worker\WorkerInterface:
        shared: false
        factory: ['App\Temporal\Factory\RuntimeFactory', 'worker']

    # Temporal classes
    App\Temporal\:
        shared: false
        resource: '../../src/Temporal/'

    App\Temporal\Runtime\RuntimeInterface: '@App\Temporal\Runtime\Runtime'
